In [7]:
import numpy as np
import matplotlib.pyplot as plt

img=np.array([[0,0,0,0,0,0],
            [0,23,12,34,22,0],
            [0,89,35,25,78,0],
            [0,67,34,21,98,0],
            [0,57,76,36,54,0],
            [0,0,0,0,0,0]]
         )
filter = np.array([[23/37,12/37,34/37],
                  [89/37,35/37,25/37],
                  [67/37,34/37,21/37]])
output = img.copy()
height,width = img.shape
for y in range(1, height - 1):
    for x in range(1, width - 1):
        s = 0
        for j in range (3):
            for i in range (3):
                pixel = int(img[y + j - 1, x + i - 1])
                s += pixel*filter[j][i]
        grey = s 
        output[y, x] = grey
print(output)

[[  0   0   0   0   0   0]
 [  0 131 297 206 219   0]
 [  0 207 477 335 290   0]
 [  0 242 490 470 298   0]
 [  0 158 305 371 182   0]
 [  0   0   0   0   0   0]]


In [9]:
img=np.array([[0,0,0,0,0,0],
            [0,23,12,34,22,0],
            [0,89,35,25,78,0],
            [0,67,34,21,98,0],
            [0,57,76,36,54,0],
            [0,0,0,0,0,0]]
         )
output = img.copy()
height,width = img.shape
for y in range(1, height - 1):
    for x in range(1, width - 1):
        window = img[y-1:y+2, x-1:x+2]
        output[y, x] = np.median(window)

print(output)

[[ 0  0  0  0  0  0]
 [ 0  0 23 22  0  0]
 [ 0 23 34 34 22  0]
 [ 0 35 36 36 25  0]
 [ 0  0 34 34  0  0]
 [ 0  0  0  0  0  0]]
